sudo: required
language: python
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_a0ecf488aafb_key -iv $encrypted_a0ecf488aafb_iv
  -in .build-bot.json -out ./datalab-travis-build-bot.json -d
- gcloud auth activate-service-account --key-file ./datalab-travis-build-bot.json
- docker pull gcr.io/cloud-datalab/datalab-gateway
script:
- docker run
  -v "$(pwd):/content/notebooks"
  -v "${HOME}:/content/datalab"
  -e "PROJECT_ID=${PROJECT_ID}"
  -e "NO_GCE_CHECK=True"
  -e "GOOGLE_APPLICATION_CREDENTIALS=/content/notebooks/datalab-travis-build-bot.json"
  --entrypoint /content/notebooks/test.sh
  --workdir /content/notebooks
  gcr.io/cloud-datalab/datalab-gateway
